Timmy development branch
BU-Spark/se-kaleidoscope-collaborative pull request #24
Opened 2024-04-22 20:27 UTC by melontimmy

Various features added, look at commits for description of work done on each file

2024-04-23 01:41 UTC, molly-yan requested changes
Good Work! There are just a few items needed to be adjusted, mainly focusing on: updating comments and TO DO parts, removing unused pieces of code, and using dynamic measurements. 

I remembered that when you showed the demo, there are pixel overflow issues when you type text in the text boxes. Please also ensure that this issue is being solved.

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/finding_location_rating/search_page_1_3.dart
> +            //FeatureBoxes(),
Is the FeatureBoxes() necessary here? If so, could you explain what is it used for?

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/screens/AddRating/review_page_1_1_overallRatingPage.dart
> +                SizedBox(height: 48),
Please replace the magic number with dynamic measurement to avoid the pixel overflow issue.

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/screens/AddRating/review_page_2_1.dart
> +                SizedBox(height: 20),
Use dynamic measurements.

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/screens/AddRating/review_page_3_1_paramterRatingPage.dart
> +                SizedBox(height: 48),
Use dynamic measurements.

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/screens/AddRating/text_review_4_1.dart
> +// TODO:
If there's no TODO, please delete this portion

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/screens/AddRating/text_review_4_1.dart
> +                      // Handle errors here, possibly show an error message to the user
Add error handler

2024-04-23 01:41 UTC, molly-yan commented on kaleidoscope_collaborative/lib/finding_location_rating/search_page_1_0.dart
> +                       * TO DO: REPLACE THIS WITH THE ACTUAL COORDINATE FROM THE SEARCH
Is the dummy coordinate here still necessary?

2024-04-29 20:40 UTC, melontimmy commented
Suggested edit:
```diff
diff --git a/README.md b/README.md
index 59d3e23..b3805cb 100644
--- a/README.md
+++ b/README.md
@@ -9,6 +9,7 @@ Kaleidoscope Collaborative aims to address the challenge faced by individuals wi
 - Patrinia Baksmaty (Founder & CEO of Kaleidoscope Collaborative)
 
 ## Developer Team
+<<<<<<< HEAD
 Fall 2023
 - Anargh Sidhardhan (Boston University)
 - Revathi Vipinachandran (Boston University)
diff --git a/kaleidoscope_collaborative/test/widget_test.dart b/kaleidoscope_collaborative/test/widget_test.dart
new file mode 100644
index 0000000..27f7b9b
--- /dev/null
+++ b/kaleidoscope_collaborative/test/widget_test.dart
@@ -0,0 +1,30 @@
+// This is a basic Flutter widget test.
+//
+// To perform an interaction with a widget in your test, use the WidgetTester
+// utility in the flutter_test package. For example, you can send tap and scroll
+// gestures. You can also use WidgetTester to find child widgets in the widget
+// tree, read text, and verify that the values of widget properties are correct.
+
+import 'package:flutter/material.dart';
+import 'package:flutter_test/flutter_test.dart';
+
+import 'package:kaleidoscope_collaborative/main.dart';
+
+void main() {
+  testWidgets('Counter increments smoke test', (WidgetTester tester) async {
+    // Build our app and trigger a frame.
+    await tester.pumpWidget(const MyApp());
+
+    // Verify that our counter starts at 0.
+    expect(find.text('0'), findsOneWidget);
+    expect(find.text('1'), findsNothing);
+
+    // Tap the '+' icon and trigger a frame.
+    await tester.tap(find.byIcon(Icons.add));
+    await tester.pump();
+
+    // Verify that our counter has incremented.
+    expect(find.text('0'), findsNothing);
+    expect(find.text('1'), findsOneWidget);
+  });
+}

```

2024-04-29 21:09 UTC, closed without merging